"""Tests for SLAM config generation via bagx tune."""

from __future__ import annotations

import re
from pathlib import Path

from typer.testing import CliRunner

from bagx.cli import app
from bagx.eval import evaluate_bag
from bagx.tune import (
    default_output_path,
    discover_tuners,
    resolve_tuner,
    tune_report,
)

runner = CliRunner()


def _strip_generated_timestamp(yaml_text: str) -> str:
    return re.sub(
        r"^# generated by bagx .+ on \d{4}-\d{2}-\d{2}T.+$",
        "# generated by bagx TEST on TIMESTAMP",
        yaml_text,
        count=1,
        flags=re.MULTILINE,
    )


class TestTuneModule:
    def test_discover_tuners_includes_builtins(self):
        names = {tuner.name for tuner in discover_tuners()}
        assert {"fast_lio", "kiss_icp"} <= names

    def test_resolve_tuner_aliases(self):
        assert resolve_tuner("fast-lio2").name == "fast_lio"
        assert resolve_tuner("kiss-icp").name == "kiss_icp"
        assert resolve_tuner("unknown") is None

    def test_default_output_path_file_and_directory(self):
        assert default_output_path("fast_lio") == Path("fast_lio_tuned.yaml")
        assert default_output_path("fast_lio", "cfg/") == Path("cfg/fast_lio_tuned.yaml")
        assert default_output_path("fast_lio", "custom.yaml") == Path("custom.yaml")

    def test_fast_lio_tune_multi_bag(self, multi_bag: Path):
        report = evaluate_bag(str(multi_bag))
        yaml_text = tune_report(report, "fast_lio")

        assert "generated by bagx" in yaml_text
        assert 'lid_topic: "/lidar"' in yaml_text
        assert 'imu_topic: "/imu"' in yaml_text
        assert "acc_cov: 0.0" in yaml_text
        assert "gyr_cov: 0.0" in yaml_text
        assert "per-point deskew" in yaml_text
        assert "bagx: not estimated, framework default" in yaml_text

    def test_kiss_icp_tune_multi_bag(self, multi_bag: Path):
        report = evaluate_bag(str(multi_bag))
        yaml_text = tune_report(report, "kiss_icp")

        assert "kiss_icp_node:" in yaml_text
        assert 'lidar_topic: "/lidar"' in yaml_text
        assert "LiDAR-only" not in yaml_text

    def test_kiss_icp_without_imu(self, gnss_bag: Path):
        report = evaluate_bag(str(gnss_bag))
        yaml_text = tune_report(report, "kiss_icp")
        assert "No IMU data" in yaml_text

    def test_fast_lio_golden_structure(self, multi_bag: Path, tmp_path: Path):
        report = evaluate_bag(str(multi_bag))
        yaml_text = _strip_generated_timestamp(tune_report(report, "fast_lio"))
        golden_path = Path(__file__).parent / "fixtures" / "tune" / "fast_lio_multi_bag.yaml"
        golden_path.parent.mkdir(parents=True, exist_ok=True)
        if not golden_path.exists():
            golden_path.write_text(yaml_text, encoding="utf-8")
        golden = _strip_generated_timestamp(golden_path.read_text(encoding="utf-8"))
        assert yaml_text == golden


class TestTuneCLI:
    def test_tune_list(self):
        result = runner.invoke(app, ["tune", "--list"])
        assert result.exit_code == 0
        assert "fast_lio" in result.output
        assert "kiss_icp" in result.output

    def test_eval_tune_writes_yaml(self, multi_bag: Path, tmp_path: Path):
        out = tmp_path / "fast_lio_tuned.yaml"
        result = runner.invoke(app, ["eval", str(multi_bag), "--tune", "fast_lio", "-o", str(out)])
        assert result.exit_code == 0, result.output
        assert out.exists()
        text = out.read_text(encoding="utf-8")
        assert 'imu_topic: "/imu"' in text
        assert "Tuned config saved to" in result.output

    def test_eval_tune_unknown_framework(self, multi_bag: Path):
        result = runner.invoke(app, ["eval", str(multi_bag), "--tune", "not_a_slam"])
        assert result.exit_code == 1
        assert "Unknown framework" in result.output
