"""Tests for eval JSON to HTML conversion."""

from __future__ import annotations

import json
import re
from pathlib import Path

from typer.testing import CliRunner

from bagx.cli import app
from bagx.eval import evaluate_bag
from bagx.report_html import eval_json_to_html, load_eval_report, write_eval_html

runner = CliRunner()


class TestReportHtml:
    def test_eval_json_to_html_contains_core_sections(self, nav2_bag: Path):
        report = evaluate_bag(str(nav2_bag)).to_dict()
        html_text = eval_json_to_html(report)

        assert "<!DOCTYPE html>" in html_text
        assert "Overall score" in html_text
        assert "Topic rates" in html_text
        assert "Findings" in html_text
        assert "nav2.detected" in html_text
        assert "/robot/odom" in html_text
        assert "generated by" in html_text
        assert "github.com/rsasaki0109/bagx" in html_text
        assert "cdnjs" not in html_text
        assert "Topic timeline" in html_text

    def test_timeline_renders_for_temporal_findings(self, gnss_bag: Path):
        report = evaluate_bag(str(gnss_bag), include_anomaly=True).to_dict()
        temporal = [f for f in report["findings"] if f.get("time_range")]
        assert temporal, "fixture should include temporal findings when anomaly is merged"
        html_text = eval_json_to_html(report)
        assert "Topic timeline" in html_text
        assert "anomaly.gnss.fix_lost" in html_text

    def test_write_and_load_round_trip(self, nav2_bag: Path, tmp_path: Path):
        json_path = tmp_path / "report.json"
        html_path = tmp_path / "report.html"
        payload = evaluate_bag(str(nav2_bag)).to_dict()
        json_path.write_text(json.dumps(payload), encoding="utf-8")

        loaded = load_eval_report(json_path)
        write_eval_html(loaded, html_path)
        html_text = html_path.read_text(encoding="utf-8")

        assert html_path.exists()
        assert re.search(r"Overall score", html_text)
        assert str(payload["overall_score"])[:4] in html_text


class TestReportHtmlCLI:
    def test_eval_html_flag(self, nav2_bag: Path, tmp_path: Path):
        html_path = tmp_path / "report.html"
        result = runner.invoke(app, ["eval", str(nav2_bag), "--html", str(html_path)])
        assert result.exit_code == 0, result.output
        assert html_path.exists()
        assert "HTML report saved to" in result.output

    def test_report_command_from_json(self, nav2_bag: Path, tmp_path: Path):
        json_path = tmp_path / "report.json"
        html_path = tmp_path / "report.html"
        payload = evaluate_bag(str(nav2_bag)).to_dict()
        json_path.write_text(json.dumps(payload), encoding="utf-8")

        result = runner.invoke(
            app,
            ["report", str(json_path), "--html", str(html_path)],
        )
        assert result.exit_code == 0, result.output
        assert "nav2.detected" in html_path.read_text(encoding="utf-8")

    def test_report_command_requires_html(self, tmp_path: Path):
        json_path = tmp_path / "report.json"
        json_path.write_text('{"report_type": "eval", "findings": []}', encoding="utf-8")
        result = runner.invoke(app, ["report", str(json_path)])
        assert result.exit_code == 2
